name: Test ubicloud image

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubicloud-standard-2-ubuntu-2204
          - ubicloud-standard-2-ubuntu-2204
          - ubicloud-standard-2-ubuntu-2204
          - ubicloud-standard-2-ubuntu-2204
          - ubicloud-standard-2-ubuntu-2204
          - ubicloud-standard-2-ubuntu-2204
          - ubicloud-standard-2-ubuntu-2204
          - ubicloud-standard-2-ubuntu-2204
          - ubicloud-standard-2-ubuntu-2204
          - ubicloud-standard-2-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - uses: ubicloud/ssh-runner@v1
        with:
          public-ssh-key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMsY2oTeeKCK8pr339MREPlai6bvnlnCX3pvCCBKoJ7c enes@cakir.web.tr"
          wait-minutes: 0
      # Metadata checks
      - run: |
          cat /proc/cpuinfo | grep 'name'| uniq >> $GITHUB_STEP_SUMMARY
      - run: uname -mr
      - run: lsb_release -a
      - run: echo $PATH
      - run: printenv
      - run: df -Th
      - run: free -h
      - run: cat /proc/meminfo
      - run: swapon -s
      - run: cat /proc/swaps
