name: Test Ubicloud Prod Runners

on:
  push:
    branches: [test-cache-all]
  # schedule:
  #   - cron: '0 * * * *'
  
jobs:
  test:
    env:
      EXPECTED_VARIABLE_COUNT: ${{ !contains(matrix.runs-on, 'arm') && 100 || 80 }}
      EXPECTED_RUNNER_ARCH: ${{ !contains(matrix.runs-on, 'arm') && 'X64' || 'ARM64' }}
      EXPECTED_ANDROID_HOME: ${{ !contains(matrix.runs-on, 'arm') && '/usr/local/lib/android/sdk' || '' }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [
          ubicloud-standard-2-ubuntu-2004, ubicloud-standard-2-ubuntu-2204, ubicloud-standard-2-ubuntu-2404, 
          ubicloud-standard-2-arm-ubuntu-2004, ubicloud-standard-2-arm-ubuntu-2204, ubicloud-standard-2-arm-ubuntu-2404
        ]
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print kernel version
        run: uname -mr

      - name: Print OS version
        run: lsb_release -a

      - name: Print environment variables
        run: printenv

      - name: Check filesystem
        run: sudo fsck -nf || [ $? -eq 4 ]

      - name: Try to update apt-get
        run: sudo apt-get update

      - name: Check Docker config
        run: |
          sudo ls -lah /etc/docker/daemon.json 
          sudo cat /etc/docker/daemon.json

      - name: Check DockerHub connectivity and limit
        run: |
          TOKEN=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitpreview/test:pull" | jq -r .token)
          curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest

      - name: Check docker pull
        run: docker pull ratelimitpreview/test:latest

      - name: Check docker internet connectivity
        run: docker run alpine ping -c 2 google.com

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v2

      - name: Print PATH
        run: echo $PATH


      - name: Verify that has environment variables more than expected count
        run: |
          count=$(env | wc -l)
          if [ "$count" -lt $EXPECTED_VARIABLE_COUNT ]; then
            echo "Environment has $count variables, expected at least $EXPECTED_VARIABLE_COUNT"
            exit 1
          fi

      - name: Verify that environment variables are set correctly
        run: |
          source ./test-helpers.sh
          expect "$HOME" "/home/runner"
          expect "$RUNNER_ARCH" "$EXPECTED_RUNNER_ARCH"
          expect "$ANDROID_HOME" "$EXPECTED_ANDROID_HOME"
          expect_path_variable "/home/runner/.cargo/bin"
          expect_path_variable "/home/runner/.config/composer/vendor/bin"
